target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'AccountDomain', :path => '../AccountDomain'
  pod 'AccountDomainv2', :path => '../AccountDomainv2'
end
